repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations
          - flake8-quotes
          - flake8-docstrings
          - flake8-picky-parentheses
        args:
          - --docstring-convention=google
          - --config=.flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - lines_after_imports = 2


  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args:
          - --config=.black
        language_version: python3.12
